version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Check that the build runs
          command: npm run build

      - run:
          name: Check that the example build runs
          command: npm run build:examples
          when: always

      - run:
          name: Check lint
          command: npm run lint
          when: always

      - run:
          name: Check prettier
          command: npm run prettier
          when: always
